# permissions for end users to edit encryptionkeyrotationcronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-csi-addons
    app.kubernetes.io/managed-by: kustomize
  name: csiaddons-encryptionkeyrotationcronjob-editor-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - encryptionkeyrotationcronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - encryptionkeyrotationcronjobs/status
  verbs:
  - get
